config/routes.rb
Rails.application.routes.draw do
  root to: "missions#new"

  resources :missions, only: %i[index create new show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/instructions_executor.rb
module InstructionsExecutor
  extend ActiveSupport::Concern

  module ClassMethods
    def execute_instructions
      self.all.each { |rover| rover.execute_instructions }
    end
  end

  def execute_instructions
    return unless self.instructions.present?
    list = self.instructions.split('')
    list.each { |instruction| execute_instruction(instruction) }
  end

  def execute_instruction(instruction)
    return unless valid_instruction?(instruction)

    command = possible_instructions[instruction.to_sym]
    self.send(command)
  end

  def valid_instruction?(instruction)
    possible_instructions.keys.include?(instruction.to_sym)
  end

  private

  def possible_instructions
    self.class.name.constantize::POSSIBLE_INSTRUCTIONS
  end
end

app/models/concerns/navigation_system.rb
#use of self for readability / references sake

module NavigationSystem
  POSSIBLE_INSTRUCTIONS = {
      L: 'turn_left',
      R: 'turn_right',
      M: 'move_forward',
    }.freeze

  {
    turn_left: { N: 'W', W: 'S', S: 'E', E: 'N' },
    turn_right: { N: 'E', E: 'S', S: 'W', W: 'N' }
  }.each do |turn, cardinals|
    define_method(turn) do
      self.update(orientation: cardinals[self.orientation.to_sym])
    end
  end

  def move_forward
   grid_step = { N: [0,1], W: [-1,0], S: [0,-1], E: [1,0] }

   x = self.position_x + grid_step[self.orientation.to_sym][0]
   y = self.position_y + grid_step[self.orientation.to_sym][1]

   self.update(position_x: x, position_y: y)
  end
end

app/models/concerns/plateaus/within_bounds_validator.rb
module Plateaus
  class WithinBoundsValidator < ActiveModel::Validator
    def validate(record)
      @record = record

      record.errors[@record.class.name.to_sym].push('out of bounds') unless within_bounds?
    end

    private

    def within_bounds?
      plateau = @record.plateau

      @record.position_x.between?(plateau.min_x, plateau.max_x) && @record.position_y.between?(plateau.min_y, plateau.max_y)
    end
  end
end

app/models/mission.rb
class Mission < ApplicationRecord
  belongs_to :plateau
  has_many :rovers

  before_create :set_mission_name

  private

  def set_mission_name
    self.name = "Mission #{self.class.last&.id.to_i + 1}"
  end
end

app/models/plateau.rb
class Plateau < ApplicationRecord
  validates :max_x, :max_y, numericality: { greater_than: 0 }
end

app/models/rover.rb
class Rover < ApplicationRecord
  include NavigationSystem
  include InstructionsExecutor

  belongs_to :mission

  validates_presence_of :position_x, :position_y, :orientation
  validates_with Plateaus::WithinBoundsValidator, if: :coordinates_changed?

  def plateau
    mission.plateau
  end

  private

  def coordinates_changed?
    (position_x.present? && position_y.present?) && (position_x_changed? || position_y_changed?)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ResponseHelper
end

app/controllers/concerns/response_helper.rb
module ResponseHelper
  def redirect_back_response(message, success: true)
    flash_type = success ? 'succes' : 'error'
    flash[flash_type.to_sym] = message
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/missions_controller.rb
class MissionsController < ApplicationController
  before_action :find_mission!, only: %i[show]

  def new; end

  def show; end

  def create
    outcome = Missions::Generator.generate_mission(params[:mission_info])

    return redirect_back_response(outcome.errors.join(', '), success: false) unless outcome.success?

    mission = outcome.result
    mission.rovers.execute_instructions

    redirect_to mission_path(mission.id)
  end

  private

  def find_mission!
    @mission = Mission.find_by_id(params[:id])
    return redirect_back_response('Mission not found', success: false) unless @mission
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_flash_message.html.erb
<div class="mt-2 text-center alert alert-danger <%= 'd-none' unless flash[:error] %>">
  <%= flash[:error] %>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light" style="background-color: #e3f2fd;">
  <a class="navbar-brand" href="<%= root_path %>">
    <%= image_tag 'xing.png', size: "40" %>
    <%= image_tag 'rocket.png', size: "20" %>
    <%= image_tag 'nasa.png', size: "40" %>
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item new-mission">
        <a class='nav-link' href="<%= new_mission_path %>">Launcher</a>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>XingTest</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
      <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <div class="container">
      <%= render 'layouts/flash_message' %>
      <%= yield %>
    </div>
  </body>


</html>

app/views/missions/new.html.erb
<div class="row justify-content-center">
  <div class="col-6">
    <div class="content">
      <h2 class="text-center">New Mission</h2>
      <div class="sample-info">
        <p><strong>Sample Input:</strong></p>
        5 5 <br>
        1 2 N <br>
        L M L M L M L M M <br>
        3 3 E <br>
        M M R M M R M R R M <br>
      </div>

      <%= form_tag missions_path, class: 'new-mission-form' do %>
        <%= text_area_tag 'mission_info', nil, class: 'form-control', rows: '4', required: true%>
        <button type="submit" class="btn btn-success">Launch</button>
      <%end%>
    </div>
  </div>
</div>

<script type="text/javascript">
  $('.new-mission').addClass('active')
</script>

app/views/missions/show.html.erb
<div class="row justify-content-center">
  <div class="col-6">
    <div class="content">
      <h2 class="text-center"><%= @mission.name %></h2>
      <h4 class="mt-4">Output: </h4>
      <div class="mt-3 mission-output card">
        <ul class="list-group list-group-flush">
          <% @mission.rovers.each do |rover| %>
            <li class="list-group-item text-center">
              <%= "#{rover.position_x} #{rover.position_y} #{rover.orientation}" %>
            </li>
          <%end%>
        </ul>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
  $('.new-mission').addClass('active')
</script>